name: Test
on:
- push
- pull_request
jobs:
  xenial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://vapor/swift:5.1-xenial
      with:
        entrypoint: swift
        args: test
